#!/usr/bin/env bash
# Re-pin every image in images.txt to its current registry digest.
#
# images.txt is GENERATED by generate-image-list.py — this script reads it and
# prints a digest-pinned copy to stdout; it never edits it in place, and edits
# to images.txt itself would be overwritten on the next generate (deploy#1171).
#
# Run after a chart bump (or before cutting an air-gapped mirror) to
# refresh the @sha256 digests. Private images (ghcr.io/zeroroot-ai/*) need a
# prior `docker login ghcr.io` / `crane auth login`. Prints a ready-to-paste
# digest-pinned list to stdout; does NOT edit images.txt in place.
#
# Usage: ./resolve-digests.sh [images.txt]
set -euo pipefail

LIST="${1:-$(dirname "$0")/images.txt}"

resolve() {
  local ref="$1" name dg
  name="${ref%@*}"        # strip any existing @sha256 digest
  name="${name%:*}"       # bare repo (for the @digest form)
  if command -v crane >/dev/null 2>&1; then
    dg="$(crane digest "$ref" 2>/dev/null || true)"
  else
    dg="$(docker manifest inspect -v "$ref" 2>/dev/null \
      | python3 -c 'import sys,json; d=json.load(sys.stdin); x=d[0] if isinstance(d,list) else d; print(x.get("Descriptor",{}).get("digest",""))' 2>/dev/null || true)"
  fi
  if [ -n "$dg" ]; then
    echo "${name}@${dg}"
  else
    echo "# UNRESOLVED (needs auth?): ${ref}"
  fi
}

while IFS= read -r line; do
  case "$line" in
    ''|\#*) echo "$line"; continue ;;
  esac
  resolve "$line"
done < "$LIST"
