#!/usr/bin/env python3
"""check-env-consumed.py — no env var injected into a first-party container that
the service never reads.

ADR-0094 layer 2, charts#294. Every guard here proves the chart can satisfy what
a workload asks for. Nothing proved the reverse, so 19 env vars were injected
into containers whose source never reads them. Two carried credentials: a
Postgres DSN on ext-authz and an SMTP password on the dashboard, mounted into
processes that never open them (hosted#351). One was a production-forbidden
billing bypass whose own comment says "CI lint should reject any values file
that sets this" — no such lint existed, and no code read the flag either
(hosted#352). One pointed the daemon at a mounted authz registry it ignores in
favour of its compiled-in copy, so editing the mounted file changed nothing on
the authorization path (hosted#353).

Three things make this checkable inside one repo.

Containers come from the committed golden renders under `helm/testdata/golden/`,
which are resolved pod specs: real image refs and real env names, no helm and no
network. The golden gate keeps them fresh.

A container is first-party when its image repository is under
`ghcr.io/zeroroot-ai/` and is not a `mirror/` re-publish. Identified by image,
never by an env-name prefix, so a new service is covered the day it ships.

Reader sets are vendored under `helm/contracts/`, generated by
`scripts/gen-env-readers.py` from each service's source and over-approximating on
purpose. `make env-contract-sync` refreshes them and a nightly job fails on
drift; the PR lane reads the committed copy so it stays single-repo.

Two consumers that are not the service's own code also count, and both were
measured as real:

  * chart-internal `${NAME}` expansion. The daemon ConfigMap writes
    `${DASHBOARD_DB_PASSWORD}` and the loader interpolates it, so the var is
    consumed by the config file rather than by a `Getenv`.
  * Kubernetes `$(NAME)` substitution. The tenant-operator builds a DSN
    containing `$(PLATFORM_PG_PASSWORD)`, which kubelet expands.

Four password vars looked dead until those two were handled. Missing either
would have deleted a working credential path.

KNOWN BLIND SPOT, and it is not small. This gate reads the golden renders, so it
sees only env vars that the baseline, eks and guest profiles actually render. A
var behind a values flag no profile sets is invisible to it. Two of the three
credential-shaped findings this slice fixed were in exactly that position and had
to be found by hand:

  * `BILLING_DEV_AUTOCONFIRM` renders only under
    `tenantOperator.billing.devAutoConfirm`, which no profile sets.
  * `GIBSON_AUTHZ_RPC_REGISTRY_PATH` renders only under
    `gibson.authz.rpcRegistry.override`, which no profile sets.

So a green run here means "nothing dead in what the profiles render", not
"nothing dead". Closing the gap needs a profile that turns every flag on, which
is a different piece of work than this gate (charts#302).

Exemptions live in `scripts/.env-consumed-exemptions.txt` as
`<container-image>:<ENV_NAME> <reason>`, keyed by name and never by line number.
A stale exemption fails the build (ADR-0094 rule 4).

  check-env-consumed.py             exit 1 on an unread env var
  check-env-consumed.py --selftest  prove the failure modes fail, then check the tree
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "helm" / "contracts"
EXEMPT_FILE = ROOT / "scripts" / ".env-consumed-exemptions.txt"

# Env vars the chart must NEVER inject, whatever the source says it reads.
#
# "Is it read?" is the wrong question for a value that bounds a security
# decision. A reader makes it tunable, and tunable in the fail-open direction
# is the defect: the operator who can widen the bound is exactly the operator
# who should not be able to. These are refused on sight, so a knob cannot come
# back by acquiring a consumer.
NEVER_INJECTED = {
    "GIBSON_IDENTITY_FRESHNESS_SKEW_SEC":
        "the anti-replay bound on the Envoy->daemon hop. Widening it widens the "
        "window in which a captured allow-decision header set replays. It is one "
        "named constant in zeroroot-ai/sdk auth/headers.go and nothing else",
}

FIRST_PARTY = re.compile(r"^ghcr\.io/zeroroot-ai/(?!mirror/)([a-z0-9-]+)")

# image name -> the service whose reader set governs it. An image with no entry
# is skipped and reported, so a new first-party image cannot be silently
# uncovered.
IMAGE_SERVICE = {
    "gibson": "gibson",
    "ext-authz": "gibson",
    "tenant-operator": "gibson",
    "platform-operator": "gibson",
    "connector-operator": "gibson",
    "gibson-bootstrap-runner": "gibson",
    "internal-authz-registry": "gibson",
    "spiffe-jwks-exporter": "gibson",
    "dashboard": "dashboard",
    "setec": "setec",
    "setec-frontend": "setec",
    "setec-node-agent": "setec",
    "setec-runtime-agent": "setec",
    "setec-installer": "setec",
    "setec-keepalive": "setec",
    "billing": "billing",
    "docs-site": "docs-site",
}
# First-party images whose source is not ours to read, so no reader set governs
# them. zitadel-login is a fork of zitadel/zitadel and reads Zitadel's own env.
UNGOVERNED = {"zitadel-login", "integrations", "sdk-registry"}

EXPANSION = re.compile(r"[\$]\{([A-Z][A-Z0-9_]*)\}|[\$]\(([A-Z][A-Z0-9_]*)\)")

# Read by a language runtime or a third-party library, so they will never appear
# in our own source and their absence is not a defect. This list is the gate's
# one piece of outside knowledge, and it is deliberately short: a name belongs
# here only when something outside this estate consumes it.
#
#   NODE_OPTIONS, NODE_EXTRA_CA_CERTS   the Node runtime
#   SSL_CERT_DIR, SSL_CERT_FILE         OpenSSL and Go's crypto/x509
#   AUTH_TRUST_HOST                     Auth.js, which the dashboard embeds
#   GODEBUG, GOMAXPROCS, GOGC           the Go runtime
#   TZ, HOME, PATH, HOSTNAME            libc and the container runtime
RUNTIME_CONSUMED = {
    "NODE_OPTIONS", "NODE_EXTRA_CA_CERTS", "NODE_ENV",
    "SSL_CERT_DIR", "SSL_CERT_FILE", "CURL_CA_BUNDLE",
    "AUTH_TRUST_HOST",
    "GODEBUG", "GOMAXPROCS", "GOGC", "GOTRACEBACK",
    "TZ", "HOME", "PATH", "HOSTNAME", "LANG", "LC_ALL",
}


def load_exemptions(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        spec, _, reason = line.partition(" ")
        out[spec.strip()] = reason.strip()
    return out


def readers(contracts: Path) -> dict[str, set[str]]:
    out: dict[str, set[str]] = {}
    if not contracts.is_dir():
        return out
    for f in sorted(contracts.glob("*-env-readers.txt")):
        svc = f.name[: -len("-env-readers.txt")]
        names = set()
        for line in f.read_text().splitlines():
            line = line.split("#")[0].strip()
            if line:
                names.add(line)
        out[svc] = names
    return out


def expansion_refs(root: Path, golden: Path) -> set[str]:
    """Names consumed by ${VAR} in a chart file or $(VAR) in a rendered manifest."""
    out: set[str] = set()

    def scan(text: str) -> None:
        for a, b in EXPANSION.findall(text):
            out.add(a or b)

    for dirpath, dirs, files in os.walk(root / "helm"):
        rel = Path(dirpath).relative_to(root / "helm")
        if rel.parts and (rel.parts[0] == "testdata" or "charts" in rel.parts):
            dirs[:] = []
            continue
        for f in files:
            if f.endswith((".yaml", ".yml", ".tpl", ".txt", ".json")):
                scan((Path(dirpath) / f).read_text(errors="replace"))
    if golden.is_dir():
        for f in sorted(golden.glob("*.yaml")):
            scan(f.read_text(errors="replace"))
    return out


def containers(golden: Path):
    """(image, container-name, [env names]) for every container in every render."""
    out = []
    if not golden.is_dir():
        return out
    for f in sorted(golden.glob("*.yaml")):
        try:
            docs = list(yaml.safe_load_all(f.read_text(errors="replace")))
        except yaml.YAMLError:
            continue
        for d in docs:
            if not isinstance(d, dict):
                continue
            for spec in _pod_specs(d):
                for key in ("containers", "initContainers"):
                    for c in spec.get(key) or []:
                        if not isinstance(c, dict):
                            continue
                        img = c.get("image")
                        if not isinstance(img, str):
                            continue
                        names = [e.get("name") for e in (c.get("env") or [])
                                 if isinstance(e, dict) and isinstance(e.get("name"), str)]
                        out.append((img, c.get("name") or "<unnamed>", names))
    return out


def _pod_specs(doc):
    """Every pod spec in a manifest, whatever wraps it."""
    found = []

    def walk(node):
        if isinstance(node, dict):
            if "containers" in node or "initContainers" in node:
                found.append(node)
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(doc)
    return found


def violations(root: Path, contracts: Path) -> tuple[list[str], list[str], list[str]]:
    """(failures, stale exemptions, ungoverned-image notes)"""
    golden = root / "helm" / "testdata" / "golden"
    reader = readers(contracts)
    expanded = expansion_refs(root, golden)
    exempt = load_exemptions(
        root / "scripts" / ".env-consumed-exemptions.txt"
    )
    used: set[str] = set()
    fail: dict[str, str] = {}
    notes: set[str] = set()

    for img, cname, names in containers(golden):
        m = FIRST_PARTY.match(img)
        if not m:
            continue
        image = m.group(1)
        svc = IMAGE_SERVICE.get(image)
        if svc is None:
            if image not in UNGOVERNED:
                notes.add(f"{image}: first-party image with no reader set; add it to "
                          f"IMAGE_SERVICE in scripts/gen-env-readers.py or to UNGOVERNED")
            continue
        allowed = reader.get(svc)
        if not allowed:
            notes.add(f"{svc}: no vendored reader set; run `make env-contract-sync`")
            continue
        for n in names:
            if n in NEVER_INJECTED:
                # Not exemptible: an exemption is for a declaration waiting on
                # its consumer, and this is a declaration that must not exist.
                fail[f"{image}:{n}"] = (
                    f"{n} is injected into the {cname} container of {image}, and it must "
                    f"never be injected: {NEVER_INJECTED[n]}")
                continue
            if n in allowed or n in expanded or n in RUNTIME_CONSUMED:
                continue
            spec = f"{image}:{n}"
            if spec in exempt:
                used.add(spec)
                continue
            fail[spec] = (f"{n} is injected into the {cname} container of {image} and the "
                          f"{svc} source never reads it")

    stale = [f"{s}  ({exempt[s] or 'no reason given'})" for s in exempt if s not in used]
    return [fail[k] for k in sorted(fail)], sorted(stale), sorted(notes)


def selftest() -> int:
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        tmp = Path(d)
        (tmp / "helm" / "testdata" / "golden").mkdir(parents=True)
        (tmp / "helm" / "x" / "templates").mkdir(parents=True)
        (tmp / "scripts").mkdir()
        c = tmp / "contracts"
        c.mkdir()
        (c / "gibson-env-readers.txt").write_text("# gen\nGIBSON_READS_THIS\nDSN\n")

        # a chart file that expands one var, so it is consumed without a Getenv
        (tmp / "helm" / "x" / "templates" / "cm.yaml").write_text(
            "data:\n  conf: |\n    password: ${GIBSON_EXPANDED}\n"
        )
        (tmp / "helm" / "testdata" / "golden" / "r.yaml").write_text(
            "apiVersion: apps/v1\nkind: Deployment\nspec:\n  template:\n    spec:\n"
            "      containers:\n"
            "        - name: daemon\n          image: ghcr.io/zeroroot-ai/gibson:v1\n"
            "          env:\n"
            "            - name: GIBSON_READS_THIS\n              value: a\n"
            "            - name: GIBSON_EXPANDED\n              value: b\n"
            "            - name: GIBSON_SUBSTITUTED\n              value: c\n"
            "            - name: GIBSON_DEAD\n              value: d\n"
            "            - name: NODE_OPTIONS\n              value: --max-old-space-size=1\n"
            "        - name: dsn\n          image: ghcr.io/zeroroot-ai/gibson:v1\n"
            "          env:\n"
            "            - name: DSN\n"
            "              value: postgres://u:$(GIBSON_SUBSTITUTED)@h/db\n"
            "        - name: upstream\n          image: docker.io/library/redis:7\n"
            "          env:\n"
            "            - name: THIRD_PARTY_ONLY\n              value: e\n"
            "        - name: fork\n          image: ghcr.io/zeroroot-ai/zitadel-login:v1\n"
            "          env:\n"
            "            - name: ZITADEL_WHATEVER\n              value: f\n"
        )
        fail, stale, notes = violations(tmp, c)
        if len(fail) != 1 or "GIBSON_DEAD" not in fail[0]:
            print(f"SELFTEST FAIL: want only GIBSON_DEAD flagged, got {fail}")
            return 1
        if stale or notes:
            print(f"SELFTEST FAIL: unexpected stale={stale} notes={notes}")
            return 1

        (tmp / "scripts" / ".env-consumed-exemptions.txt").write_text(
            "gibson:GIBSON_DEAD tracked in a follow-up\n"
            "gibson:GONE_AWAY target no longer fails\n"
        )
        fail, stale, _ = violations(tmp, c)
        if fail:
            print(f"SELFTEST FAIL: the exemption should silence it, got {fail}")
            return 1
        if len(stale) != 1 or not stale[0].startswith("gibson:GONE_AWAY"):
            print(f"SELFTEST FAIL: want gibson:GONE_AWAY stale, got {stale}")
            return 1

        # A NEVER_INJECTED var fails even when the service reads it, and even
        # with an exemption written for it. Both are the ways it would come
        # back: acquire a consumer, or get silenced.
        never = next(iter(NEVER_INJECTED))
        (c / "gibson-env-readers.txt").write_text(f"# gen\nGIBSON_READS_THIS\nDSN\n{never}\n")
        (tmp / "scripts" / ".env-consumed-exemptions.txt").write_text(
            f"gibson:GIBSON_DEAD tracked in a follow-up\n"
            f"gibson:GONE_AWAY target no longer fails\n"
            f"gibson:{never} silenced, which must not work\n"
        )
        golden = tmp / "helm" / "testdata" / "golden" / "r.yaml"
        golden.write_text(golden.read_text().replace(
            "            - name: GIBSON_DEAD\n              value: d\n",
            f"            - name: GIBSON_DEAD\n              value: d\n"
            f"            - name: {never}\n              value: \"60\"\n"))
        fail, _, _ = violations(tmp, c)
        if not any(never in f and "must never be injected" in f for f in fail):
            print(f"SELFTEST FAIL: {never} is read AND exempted and must still fail, got {fail}")
            return 1

    fail, stale, notes = violations(ROOT, CONTRACTS)
    if fail or stale or notes:
        print("SELFTEST FAIL: the tree has env violations:\n  " + "\n  ".join(fail + stale + notes))
        return 1
    print("✅ self-test: an unread var fails, a var that must never be injected fails even when "
          "read and exempted; a ${VAR}-expanded one, a $(VAR)-substituted one, a third-party "
          "image and a fork are not judged; an exemption silences and a stale one fails")
    return 0


def main() -> int:
    if "--selftest" in sys.argv:
        return selftest()
    fail, stale, notes = violations(ROOT, CONTRACTS)
    for f in fail:
        print("::error::" + f)
    for s in stale:
        print("::error::stale exemption, delete the line: " + s)
    for n in notes:
        print("::error::" + n)
    if fail or stale or notes:
        return 1
    print("ok: every env var injected into a first-party container is read by that service")
    return 0


if __name__ == "__main__":
    sys.exit(main())
