#!/usr/bin/env python3
"""gen-operator-rbac.py — vendor each gibson operator's own RBAC role.

An operator's controllers declare what they read and write with kubebuilder
markers, and controller-gen writes the result to
operators/<name>/config/rbac/role.yaml in the gibson repo. This chart grants
the operator its ClusterRole by hand. When a gibson release adds a controller,
the generated role grows and the chart's role does not. The operator then
starts, cannot list a kind it watches, and its informer never syncs: gibson
v0.153.0 added the TenantIdentity controller, and a fresh install of charts
0.136.5 never gave the first tenant its Zitadel org.

This script copies each generated role, AT THE TAG THE CHART PINS, into
helm/contracts/. check-operator-rbac-covers.py then proves offline, at PR
time, that the chart grants at least that role. The nightly
env-contract-fresh run proves that the copy matches the tag.

  gen-operator-rbac.py --write    refresh helm/contracts/gibson-operator-rbac-*.yaml
  gen-operator-rbac.py --check    exit 1 when a committed copy is stale
"""
from __future__ import annotations

import sys
from pathlib import Path

from pinned_source import pinned_tag, tree_at

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "helm" / "contracts"
# The operators that publish a generated role. The platform-operator publishes
# one since gibson v0.153.1 (gibson#768): its markers stood in a type doc
# comment before, where controller-gen ignores them.
OPERATORS = ("tenant", "connector", "platform")


def render(op: str, tag: str, body: str) -> str:
    return (
        f"# gibson-operator-rbac-{op}.yaml — GENERATED by scripts/gen-operator-rbac.py.\n"
        "# Do not hand-edit. Refresh with `make operator-rbac-sync`.\n"
        "#\n"
        f"# The {op}-operator's own ClusterRole, as controller-gen wrote it from the\n"
        "# kubebuilder markers of its controllers. check-operator-rbac-covers.py fails\n"
        "# the build when the chart grants the operator less than this.\n"
        "#\n"
        f"# Source: zeroroot-ai/gibson @ {tag}\n"
        + body
    )


def main() -> int:
    write, check = "--write" in sys.argv, "--check" in sys.argv
    if not (write or check):
        print(__doc__)
        return 2
    tag = pinned_tag("gibson")
    stale = []
    with tree_at("gibson", tag) as tree:
        for op in OPERATORS:
            src = Path(tree) / "operators" / op / "config" / "rbac" / "role.yaml"
            if not src.is_file():
                print(f"::error::gibson {tag} holds no operators/{op}/config/rbac/role.yaml")
                return 2
            text = render(op, tag, src.read_text())
            target = OUT / f"gibson-operator-rbac-{op}.yaml"
            if write:
                target.write_text(text)
                print(f"  wrote {target.relative_to(ROOT)}  (at {tag})")
            elif not target.exists() or target.read_text() != text:
                stale.append(f"{target.relative_to(ROOT)} differs from gibson at {tag}")
    for s in stale:
        print("::error::stale operator role: " + s + " — run `make operator-rbac-sync`")
    if stale:
        return 1
    if check:
        print(f"ok: every vendored operator role matches gibson at {tag}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
