#!/usr/bin/env python3
"""gen-grpc-methods.py: the gRPC methods that the gibson daemon serves, as a contract.

The edge routes a request by the gRPC path `/<package>.<Service>/<Method>`.
A route for a service that no proto file defines matches no request, and its
rate limit applies to nothing (charts#356). The services live in a different
repository, so a guard cannot read them when a pull request runs.

The generated authz registry of gibson has one entry for each method that the
daemon serves: the daemon does not start when a served method has no entry.
This script reads the registry at the tag that the chart pins and commits the
method paths as helm/contracts/gibson-grpc-methods.txt.
scripts/check-edge-grpc-routes.py reads that file with no network and no
sibling checkout. env-contract-fresh.yml extracts it again each night.

  gen-grpc-methods.py --write    rewrite the contract from the sibling checkout
  gen-grpc-methods.py --check    fail when the committed contract is stale
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

from pinned_source import pinned_tag, tree_at

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "helm" / "contracts" / "gibson-grpc-methods.txt"
REGISTRY = "internal/platform/authz/registry/registry.yaml"
METHOD = re.compile(r'^  "(/[A-Za-z0-9_.]+/[A-Za-z0-9_]+)":\s*$', re.M)


def extract(text: str) -> list[str]:
    return sorted(set(METHOD.findall(text)))


def render(tag: str, methods: list[str]) -> str:
    services = {m.rsplit("/", 1)[0] for m in methods}
    return (
        "# gibson-grpc-methods.txt: GENERATED by scripts/gen-grpc-methods.py.\n"
        "# Do not hand-edit. Refresh with `make env-contract-sync`.\n"
        "#\n"
        "# Each gRPC method that the gibson daemon serves, from the generated authz\n"
        f"# registry ({REGISTRY}).\n"
        "# An edge route for a service that is not in this list matches no request.\n"
        "#\n"
        f"# {len(methods)} method(s) of {len(services)} service(s).\n"
        "#\n"
        f"# Source: zeroroot-ai/gibson @ {tag}\n"
        "#\n"
        + "".join(f"{m}\n" for m in methods)
    )


def main() -> int:
    write, check = "--write" in sys.argv, "--check" in sys.argv
    if write == check:
        print(__doc__)
        return 2
    tag = pinned_tag("gibson")
    with tree_at("gibson", tag) as tmp:
        src = Path(tmp) / REGISTRY
        if not src.is_file():
            print(f"::error::gibson {tag} holds no {REGISTRY}")
            return 2
        methods = extract(src.read_text())
    if len(methods) < 100:
        print(f"::error::read {len(methods)} method(s) from the registry of gibson {tag}; "
              "the parser found too few, so the registry format changed")
        return 2
    text = render(tag, methods)
    if write:
        OUT.write_text(text)
        print(f"  wrote {OUT.relative_to(ROOT)}  ({len(methods)} methods at {tag})")
        return 0
    if not OUT.exists() or OUT.read_text() != text:
        print(f"::error::stale contract: {OUT.relative_to(ROOT)} differs from gibson at {tag}. Run `make env-contract-sync`")
        return 1
    print(f"ok: {OUT.relative_to(ROOT)} matches the authz registry of gibson at {tag}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
