#!/usr/bin/env python3
"""Vendor the operator CRDs into gibson-crds from the umbrella's pinned subcharts.

ADR-0015 and deploy#1728. The umbrella owns cert-manager, external-secrets
and the CloudNativePG operator as subcharts and renders CRs of all three
(Certificate, Issuer, ExternalSecret, ClusterSecretStore, Cluster). Helm
refuses a CRD and a CR of that CRD in one release (deploy#1627), so the
subcharts render with their CRDs OFF and this script copies those CRDs, from
the exact chart version helm/gibson/Chart.yaml pins, into

    helm/gibson-operator-crds/files/crds/<chart>.yaml

a first-party chart that gibson-crds carries as a file:// dependency and whose
templates/crds.yaml includes them verbatim through .Files.Get (the CRD
descriptions contain `{{ }}` examples that would not survive Helm
templating). Each CRD gets `helm.sh/resource-policy: keep`, like every other
CRD gibson-crds ships. It is a dependency and not files of gibson-crds
because a Helm release record stores the top-level chart's files as well as
the manifest, under a 1 MiB cap (see that chart's Chart.yaml).

ONE SOURCE OF TRUTH. The chart version comes from helm/gibson/Chart.yaml and
the CRDs come from the tarball `helm dependency update` put in
helm/gibson/charts/. Bump the version and --check fails until you rerun this
script; there is no second pin to forget.

Modes:
    (default)    regenerate helm/gibson-operator-crds/files/crds/*.yaml
    --check      exit 1 when a committed file differs from a fresh render
                 (compared as parsed YAML, so a PyYAML formatting difference
                 between two machines is not drift)
    --selftest   prove --check fails on a mutated copy (exit 2 if it cannot)

Needs helm on PATH and the umbrella's charts/ built (`make chart-deps`).
Exit: 0 ok · 1 drift or missing input · 2 self-test broken
"""

from __future__ import annotations

import copy
import pathlib
import subprocess
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
UMBRELLA = ROOT / "helm" / "gibson"
DEST = ROOT / "helm" / "gibson-operator-crds" / "files" / "crds"

# chart name -> the values that make the upstream chart render its CRDs.
OPERATORS: dict[str, list[str]] = {
    "cert-manager": ["crds.enabled=true", "crds.keep=false"],
    "external-secrets": ["installCRDs=true"],
    "cloudnative-pg": ["crds.create=true"],
}
KEEP = {"helm.sh/resource-policy": "keep"}

# Upstream provenance for the NOTICE and the per-file header. Apache-2.0
# section 4 requires the license and attribution to travel with a
# redistribution, and these files ARE a verbatim redistribution.
UPSTREAM: dict[str, tuple[str, str]] = {
    "cert-manager": ("Apache-2.0", "https://github.com/cert-manager/cert-manager"),
    "external-secrets": ("Apache-2.0", "https://github.com/external-secrets/external-secrets"),
    "cloudnative-pg": ("Apache-2.0", "https://github.com/cloudnative-pg/charts"),
}


def pinned_versions() -> dict[str, str]:
    chart = yaml.safe_load((UMBRELLA / "Chart.yaml").read_text())
    return {d["name"]: d["version"] for d in chart.get("dependencies", [])}


def tarball(name: str, version: str) -> pathlib.Path:
    tgz = UMBRELLA / "charts" / f"{name}-{version}.tgz"
    if not tgz.exists():
        sys.exit(
            f"ERROR: {tgz.relative_to(ROOT)} is missing. Run `make chart-deps` first: "
            "the vendored CRDs come from the packaged subchart, never from the network."
        )
    return tgz


def render_crds(name: str, version: str) -> list[dict]:
    cmd = ["helm", "template", "gibson-crds", str(tarball(name, version)),
           "--namespace", "gibson"]
    for kv in OPERATORS[name]:
        cmd += ["--set", kv]
    out = subprocess.run(cmd, check=True, capture_output=True, text=True).stdout
    docs = []
    for d in yaml.safe_load_all(out):
        if not isinstance(d, dict) or d.get("kind") != "CustomResourceDefinition":
            continue
        d = copy.deepcopy(d)
        md = d.setdefault("metadata", {})
        ann = md.get("annotations") or {}
        ann.update(KEEP)
        md["annotations"] = ann
        docs.append(d)
    docs.sort(key=lambda d: d["metadata"]["name"])
    if not docs:
        sys.exit(f"ERROR: {name} {version} rendered no CustomResourceDefinition with {OPERATORS[name]}")
    return docs


def dump(name: str, version: str, docs: list[dict]) -> str:
    license, upstream = UPSTREAM[name]
    header = (
        f"# GENERATED by scripts/vendor-operator-crds.py from {name}-{version}.tgz.\n"
        "# Do not edit. Bump the version in helm/gibson/Chart.yaml, run\n"
        "# `make vendor-operators`, and commit the result.\n"
        "#\n"
        f"# Upstream: {upstream}\n"
        f"# License:  {license} — full text in LICENSES/{license}.txt, attribution in NOTICE.\n"
        "# This file is a VERBATIM redistribution of that project's CRDs.\n"
    )
    body = yaml.safe_dump_all(docs, sort_keys=False, width=1 << 20, allow_unicode=True,
                              explicit_start=True)
    return header + body


def load_committed(path: pathlib.Path) -> list[dict]:
    if not path.exists():
        return []
    return [d for d in yaml.safe_load_all(path.read_text()) if isinstance(d, dict)]


def check(versions: dict[str, str]) -> list[str]:
    problems = []
    for name in OPERATORS:
        fresh = render_crds(name, versions[name])
        path = DEST / f"{name}.yaml"
        committed = load_committed(path)
        if committed != fresh:
            problems.append(
                f"{path.relative_to(ROOT)} differs from {name}-{versions[name]}.tgz "
                f"({len(committed)} committed vs {len(fresh)} rendered CRDs)"
            )
    return problems


def selftest(versions: dict[str, str]) -> int:
    name = "cloudnative-pg"
    fresh = render_crds(name, versions[name])
    mutated = fresh[1:]  # drop one CRD
    if mutated == fresh:
        print("GUARD BROKEN: dropping a CRD produced an identical document set", file=sys.stderr)
        return 2
    # And an annotation change must count: keep is what makes a CRD survive uninstall.
    mutated2 = copy.deepcopy(fresh)
    mutated2[0]["metadata"]["annotations"].pop("helm.sh/resource-policy")
    if mutated2 == fresh:
        print("GUARD BROKEN: removing resource-policy: keep was not detected", file=sys.stderr)
        return 2
    print("✅ selftest passed: --check detects a dropped CRD and a dropped keep annotation")
    return 0


def main(argv: list[str]) -> int:
    versions = pinned_versions()
    missing = [n for n in OPERATORS if n not in versions]
    if missing:
        print(f"ERROR: helm/gibson/Chart.yaml no longer lists {missing}; the umbrella must own them (deploy#1728)")
        return 1
    if "--selftest" in argv:
        return selftest(versions)
    if "--check" in argv:
        problems = check(versions)
        if problems:
            print("❌ vendored operator CRDs are stale:")
            for p in problems:
                print(f"   {p}")
            print("   Run `make vendor-operators` and commit helm/gibson-operator-crds/files/crds/.")
            return 1
        print("✅ vendored operator CRDs match the pinned subcharts")
        return 0
    DEST.mkdir(parents=True, exist_ok=True)
    for name in OPERATORS:
        docs = render_crds(name, versions[name])
        path = DEST / f"{name}.yaml"
        path.write_text(dump(name, versions[name], docs))
        print(f"  wrote {path.relative_to(ROOT)} ({len(docs)} CRDs from {name}-{versions[name]})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
